package bo.ylb.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OperadorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperadorAllPropertiesEquals(Operador expected, Operador actual) {
        assertOperadorAutoGeneratedPropertiesEquals(expected, actual);
        assertOperadorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperadorAllUpdatablePropertiesEquals(Operador expected, Operador actual) {
        assertOperadorUpdatableFieldsEquals(expected, actual);
        assertOperadorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperadorAutoGeneratedPropertiesEquals(Operador expected, Operador actual) {
        assertThat(actual)
            .as("Verify Operador auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperadorUpdatableFieldsEquals(Operador expected, Operador actual) {
        assertThat(actual)
            .as("Verify Operador relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getNacionalidad()).as("check nacionalidad").isEqualTo(expected.getNacionalidad()))
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperadorUpdatableRelationshipsEquals(Operador expected, Operador actual) {
        // empty method
    }
}
